backend:
  name: github
  repo: invmv/astro-docs-priceaction
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://docs.invmy.us.kg
  auth_endpoint: /api/auth
media_folder: public/uploads
public_folder: /uploads
# collections:
#   - name: "docs"
#     label: "文档"
#     folder: "src/content/docs"
#     create: true
#     fields:
#       - { name: "title", label: "标题", widget: "string" }
#       - { name: "description", label: "描述", widget: "text" }
#       - { name: "body", label: "正文", widget: "markdown",modes: ["raw","rich_text"] }
collections:
  - name: "Home"
    label: "Home"
    folder: "src/content/docs"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "description", label: "描述", widget: "text" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["raw","rich_text"] }

  - name: "Basic"
    label: "Basic"
    folder: "src/content/docs/basic"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "description", label: "描述", widget: "text" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["raw","rich_text"] }

  - name: "Rule"
    label: "Rule"
    folder: "src/content/docs/rule"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "description", label: "描述", widget: "text" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["raw","rich_text"] }

  - name: "trade"
    label: "trade"
    folder: "src/content/docs/trade"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "description", label: "描述", widget: "text" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["raw","rich_text"] }

  - name: "other"
    label: "other"
    folder: "src/content/docs/other"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "description", label: "描述", widget: "text" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["raw","rich_text"] }