backend:
  name: github
  repo: invmv/astro-docs-priceaction
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://docs.invmy.us.kg/
  auth_endpoint: /api/auth
media_folder: public/uploads
public_folder: /uploads
collections:
  - name: "docs" # 集合名称
    label: "文档" # 在 CMS 中的显示标签
    folder: "src/content/docs" # 文档存储的根目录
    create: true # 允许从 CMS 创建新文档
    nested: # 启用嵌套文件夹支持
      depth: 2 # 允许的子文件夹层级（可根据需要调整）
    slug: "{{slug}}" # 文件名生成方式
    fields:
      - { label: "标题", name: "title", widget: "string" } # 标题字段
      - { label: "描述", name: "description", widget: "text" } # 描述字段
      - { label: "正文字段", name: "body", widget: "markdown" } # 正文字段