backend:
  name: github
  repo: invmv/astro-docs-priceaction
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://docs.invmy.us.kg
  auth_endpoint: /api/auth
media_folder: public/uploads
public_folder: /uploads
# collections:
#   - name: ""
#     label: ""
#     folder: "src/content/"
#     create: true
#     fields:
#       - { name: "title", label: "标题", widget: "string" }
#       - { name: "body", label: "正文", widget: "markdown",modes: ["rich_text","raw"] }
collections:
  - name: "pages"
    label: "pages"
    folder: "src/content/docs"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["rich_text","raw"] }

  - name: "more"
    label: "more"
    folder: "src/content/more"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["rich_text","raw"] }
      
  - name: "Traders"
    label: "Traders"
    folder: "src/content/docs/traders"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["rich_text","raw"] }

  - name: "rule"
    label: "rule"
    folder: "src/content/docs/rule"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["rich_text","raw"] }

  - name: "basic"
    label: "basic"
    folder: "src/content/docs/basic"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["rich_text","raw"] }

  - name: "trading"
    label: "trading"
    folder: "src/content/docs/trading"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["rich_text","raw"] }