backend:
  name: github
  repo: invmv/astro-docs-priceaction
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://docs.invmy.us.kg
  auth_endpoint: /api/auth
media_folder: public/uploads
public_folder: /uploads
collections:
  - name: "docs"
    label: "文档"
    folder: "src/content/docs"
    create: true
    slug: "{{slug}}" # 新文档默认 slug
    nested:          # 启用嵌套分类结构
      depth: 4      # 允许的嵌套级别
      summary: '{{title}}' 
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "description", label: "描述", widget: "text" }
      - { name: "body", label: "正文", widget: "markdown",modes: ["raw","rich_text"] }
